### ISSUE TITLE
Try the model without the similarities

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/path2vec#14]
Generate results similar to https://docs.google.com/spreadsheets/d/1esXh-eNz76_86PikQe9-FwkeEpMz7Of6rzeiSS6lrD8/edit#gid=1778525383, but ONLY using L2 regularization and regularization using nearest neighbours (the 'main' training data are not used at all in the form of the pair similarities).

**Comment by akutuzov** [comment]
...and with using the main training data and the nearest neighbors regularization (but without L2 or L1).

**Comment by m-dorgham** [comment]
@alexanderpanchenko what do you mean by "the 'main' training data are not used at all in the form of the pair similarities"??
Could you elaborate please.

**Comment by alexanderpanchenko** [comment]
I mean using only the 'regularizers' as the objective (the ones you added in your work).

**Comment by m-dorgham** [comment]
Here are the results:
https://docs.google.com/spreadsheets/d/1esXh-eNz76_86PikQe9-FwkeEpMz7Of6rzeiSS6lrD8/edit#gid=2028670185

**Comment by alexanderpanchenko** [comment]
probably it will not change much, but just as a santy check please re-train also with beta=gamma=1.0

**Comment by m-dorgham** [comment]
Ok. Will do it.
