### ISSUE TITLE
Add results of node2vec 600 to the paper to figure Figure 3

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/path2vec#15]

**Comment by snkohail** [comment]
Where to ?

**Comment by snkohail** [comment]
Thanks @akutuzov

**Comment by akutuzov** [comment]
@snkohail is this the node2vec 600 model you trained?
http://ltdata1.informatik.uni-hamburg.de/shortest_path/models/converted_wordnet.600.10.70.5.F.emb.gz

**Comment by akutuzov** [comment]
@snkohail have you trained node2vec embeddings with the dimensionality 600 and 25 random walks? I see only 5-walk models results in the googledoc.

**Comment by akutuzov** [comment]
I updated the tables with the nodevec600 results and [created](https://github.com/uhh-lt/path2vec/commit/dd5a1e6db089608924bd40e2919f40aff34257ed) new plots. They are already in the Overleaf paper.
Node2vec seems to radically improve when moving from 300 to 600 dimensions. However, it can be explained by the fact that the hyperparameters of 300D and 600D models are different: 300D were trained with 25 random walks for 10 epochs and 600d were trained with 5 random walks for 5 epochs. 
Anyway, these results do not significantly change the overall picture.

**Comment by alexanderpanchenko** [comment]
Thanks! 

@snkohail we are preparing a new submission for NAACL. Could you compute node2vec with the same hyperparameters as for 600 dimensions for the dimensions 300, 200, 100, and 50?

**Comment by snkohail** [comment]
@alexanderpanchenko Yes, on it.

**Comment by alexanderpanchenko** [comment]
Great,  thanks!

**Comment by snkohail** [comment]
I am getting this error when I run node2vec on the server (gpu or cpu1). 
cannot execute binary file: Exec format error
I had no problem running the script b4 ?!
Any help?

**Comment by alexanderpanchenko** [comment]
Can you provide the command you launch and the full error msg?

Did you try to recompile?

**Comment by snkohail** [comment]
it is the node2vec script:
./node2vec -i:graph/karate.edgelist -o:emb/karate.emb -l:3 -d:24 -p:0.3 -dr -v

the same script runs normally in my computer, I am running it now.

I tried both node2vec compiled on my computer and moved to the server, and another one compiled on the server. both gives the same error. Even the one which I used before in my experiments didn't work. 
I googled the error. seems something with the bash cofig or directory. But I don't have sudo permission to do the solutions.

**Comment by snkohail** [comment]
Sorry, but I had to run the experiments on my computer coz I don't have permission to run shell scripts. I also couldn't upload the results to the server. Please find all the embeddings of size 600 here:

https://drive.google.com/open?id=1SbegQaXxH_t3BqKeGsdkyTC5UUYcprvj

**Comment by alexanderpanchenko** [comment]
thanks! sounds stange you do not have the rights - ask Steffen to fix that on ltcpu1

**Comment by alexanderpanchenko** [comment]
@Andrei /@Sarah could you compute the performance on this new model please?

**Comment by akutuzov** [comment]
@snkohail  thanks!
@alexanderpanchenko but should we use the 600D models with the hyperparameters used for models of lower dimensionalities, or should we instead use the scores of those lower-dimensional models with  5 random walks and 5 epochs, as in the original 600-D model by @snkohail ? What do you think?

**Comment by akutuzov** [comment]
OK, I think will be less time-consuming if we simply use the hyperparameters which we already used before (25 random walks, context size 10, 10 epochs). I updated the node2vec results in our tables with the scores for node2vec.600.25.10.10 model and recreated the plots in the paper using these scores. 
As I've said, it does not change the overall picture anyway.

**Comment by alexanderpanchenko** [comment]
Thanks! Sounds good to me: I have no special opinion about it.

**Comment by akutuzov** [comment]
@snkohail Where can I find the node2vec models you trained before?
http://ltdata1.informatik.uni-hamburg.de/shortest_path/models/ certainly does not have all of them.
For example, what about the 300_25_10_10 model?
