### ISSUE TITLE
Make the batch generator thread-safe

### ISSUE THREAD

**Issue by akutuzov** [uhh-lt/path2vec#21]
https://github.com/keras-team/keras/issues/1638

https://stackoverflow.com/questions/41194726/python-generator-thread-safety-using-keras

**Comment by alexanderpanchenko** [comment]
should we close this one?

**Comment by akutuzov** [comment]
It would be nice if someone took this over, I most probably won't have time for that in the nearest week,
But it should be done.

**Comment by alexanderpanchenko** [comment]
ok

**Comment by akutuzov** [comment]
It seems that the overhead of using thread-safe batch generators will actually destroy the benefits of using multiple workers in this case. Easier to simply increase the batch size. Closing the issue.
