### ISSUE TITLE
Redraw the plot

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/path2vec#25]
<img width="703" alt="image" src="https://user-images.githubusercontent.com/1456830/49151032-faf12700-f30e-11e8-8c84-240da4f3b631.png">

- remove number prefix for words

- add the original words below 

- try making labels bold font 

- make the connections and nodes blue (but the selected sensese are red)

- make connections blue as well

- encode the weight of the connection with the thickness of the line

**Comment by m-dorgham** [comment]
What do you think about these figures?

/home/dorgham/Figure_1.png

/home/dorgham/Figure_2.png

/home/dorgham/Figure_3.png

**Comment by alexanderpanchenko** [comment]
Thanks - it looks much better now.

1. Please make the font of word nbelow ca twice as larger. 

2. Set the color of the connections to the same one as the color of the blue nodes.

3. Also enlarge font of the size of th nodes a bit.

4. Keep only the last example (what is the sentence by the way?)

**Comment by m-dorgham** [comment]
Look at these pics for the last sentence with the changes you asked. These are 3 pics with different edge thickness.

![figure_3](https://user-images.githubusercontent.com/32111487/49406045-b6bdb680-f754-11e8-8c63-69838dc9e2e4.png)
![figure_5](https://user-images.githubusercontent.com/32111487/49406046-b6bdb680-f754-11e8-8cb9-98038be2888e.png)
![figure_6](https://user-images.githubusercontent.com/32111487/49406047-b6bdb680-f754-11e8-94d9-0c478d02c8b3.png)

This graph is part of the whole graph generated for the sentence: More often than not, ringers think of the church as something stuck on the bottom of the belfry.
Here is the whole graph:

![figure_4](https://user-images.githubusercontent.com/32111487/49406454-f33de200-f755-11e8-9fab-9b76ca370085.png)

**Comment by alexanderpanchenko** [comment]
The most thick one is the best IMO. 

1. Is this one takes into account edge pruning with the threshold?

2. Please make the original words below bigger even more.

**Comment by m-dorgham** [comment]
1. yes I did edge pruning in this image but with a small threshold.

2. ok I will.

**Comment by alexanderpanchenko** [comment]
> On 4. Dec 2018, at 14:02, Mohammad Dorgham <notifications@github.com> wrote:
> 
> yes I did edge pruning in this image but with a small threshold.
> 

Ok. I see.
> 
> ok I will.
> 

Thanks!

**Comment by alexanderpanchenko** [comment]
@m-dorgham i checked the image again, it all looks good but I just need a copy of this one 

<img width="594" alt="image" src="https://user-images.githubusercontent.com/1456830/49523863-e383e200-f8aa-11e8-85f0-404f494d9eb4.png">

with much larger font on the bottom (AND you can make the connections even thicker ...)

**Comment by m-dorgham** [comment]
@alexanderpanchenko Is this one fine?

![figure_7](https://user-images.githubusercontent.com/32111487/49544524-4ee5a800-f8db-11e8-81c6-5d7cce11c7f3.png)

**Comment by alexanderpanchenko** [comment]
Thanks, perfect
