### ISSUE TITLE
Improvements in the embeddings script

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/path2vec#8]
1. Add command line interface using argparse. These parameters should be configurable using argparse: 

```

  trainfile = sys.argv[1]  # Gzipped file with pairs and their similarities
  embedding_dimension = int(sys.argv[2])  # vector size (for example, 20)
  batch_size = int(sys.argv[3])  # number of pairs in a batch (for example, 10)
  learn_rate = float(sys.argv[4])   # Learning rate
  
  negative = 3  # number of negative samples

```

2. Merge embeddings_2.py and embeddings.py. Add the changes in the new script to the old one making them optional. Add a special argument (**turned off by default**) like ``--use-neighbours`` and ``--number-of-neighbours`` which controls the number of used nearest neighbours.

**Comment by alexanderpanchenko** [comment]
please indicate in the commit message the number of the ticket so that it is possible to see what changed you've done e.g. ``git commit -a -m  'refactoring of the cli tools #8'``

**Comment by m-dorgham** [comment]
@alexanderpanchenko Ok, will do.
